server:
  port: 8181
spring:
  application:
    name: messages-service
  profiles:
    active: local
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9191/realms/luan-apps
